# Generated by Django 4.2.4 on 2024-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=45, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='api_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='device_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='protocol',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('http', 'HTTP')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='software_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='device_token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='pub_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
