# Generated by Django 4.2.4 on 2024-08-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0003_httpssettings_setting_alter_mqttsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='received_data',
            field=models.JSONField(),
        ),
    ]
