# Generated by Django 4.2.4 on 2024-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0004_alter_logdata_received_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HttpsSettings',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AlterModelOptions(
            name='mqttsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='mqttsettings',
            name='keepalive',
        ),
        migrations.RemoveField(
            model_name='mqttsettings',
            name='pub_topic',
        ),
        migrations.RemoveField(
            model_name='mqttsettings',
            name='qos',
        ),
        migrations.RemoveField(
            model_name='mqttsettings',
            name='server_name_alias',
        ),
        migrations.RemoveField(
            model_name='mqttsettings',
            name='sub_topic',
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
