# Generated by Django 4.2.4 on 2024-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0005_delete_httpssettings_delete_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Https',
                'verbose_name_plural': 'Https',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_printing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mqttsettings',
            options={'verbose_name': 'Mqtt', 'verbose_name_plural': 'Mqtt'},
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='keepalive',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='pub_topic',
            field=models.CharField(default='default/pub/topic', max_length=255),
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='qos',
            field=models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=0),
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='server_name_alias',
            field=models.CharField(default='default', max_length=45),
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='sub_topic',
            field=models.CharField(default='default/sub/topic', max_length=255),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='host',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='password',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='username',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
